project_id = "kedwqqhknmqivqyrwnqj"

[functions.analyze-resume]
verify_jwt = false

[functions.generate-roadmap]
verify_jwt = false

[functions.mock-interview]
verify_jwt = false

[functions.support-chat]
verify_jwt = false